apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingresscontroler
  namespace: ingress
  helmVersion: v3
spec:
  releaseName: nginxic
  chart:
    git: https://github.com/seitosan/fluxcd_bootstrap
    ref: master
    path: charts/nginx
  values:
    serviceName: ingresscontroller
