apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-Controler
  namespace: arc-k8s-demo
  helmVersion: v3
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/seitosan/fluxcd_bootstrap
    ref: main
    path: charts/nginx
  values:
    serviceName: arc-k8s-demo
